/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email + password
         * @description Email + password -> JWT access/refresh pair.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["classes_list"];
        put?: never;
        post: operations["classes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["classes_retrieve"];
        put: operations["classes_update"];
        post?: never;
        delete: operations["classes_destroy"];
        options?: never;
        head?: never;
        patch: operations["classes_partial_update"];
        trace?: never;
    };
    "/api/classes/{id}/assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or create assignments for a class */
        get: operations["classes_assignments_list"];
        put?: never;
        /** List or create assignments for a class */
        post: operations["classes_assignments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{id}/lesson-plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or create lesson plans for a class */
        get: operations["classes_lesson_plans_list"];
        put?: never;
        /** List or create lesson plans for a class */
        post: operations["classes_lesson_plans_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{id}/students/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List students in a class, or enroll one */
        get: operations["classes_students_list"];
        put?: never;
        /** List students in a class, or enroll one */
        post: operations["classes_students_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{id}/students/{student_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a student from a class */
        delete: operations["classes_students_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exercises_retrieve"];
        put?: never;
        post?: never;
        delete: operations["exercises_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}/submissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List submissions for an exercise (teacher/admin) */
        get: operations["exercises_submissions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["feedback_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["modules_list"];
        put?: never;
        post: operations["modules_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["modules_retrieve"];
        put: operations["modules_update"];
        post?: never;
        delete: operations["modules_destroy"];
        options?: never;
        head?: never;
        patch: operations["modules_partial_update"];
        trace?: never;
    };
    "/api/modules/{id}/exercises/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or create exercises within a module */
        get: operations["modules_exercises_list"];
        put?: never;
        /** List or create exercises within a module */
        post: operations["modules_exercises_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert the current student's progress for a module
         * @description Upsert progress for (student, module). POST /api/progress/.
         */
        post: operations["progress_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current student's module progress */
        get: operations["progress_me_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submissions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}/feedback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List feedback on a submission */
        get: operations["submissions_feedback_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current student's own submissions */
        get: operations["submissions_me_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_list"];
        put?: never;
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_retrieve"];
        put: operations["users_update"];
        post?: never;
        delete: operations["users_destroy"];
        options?: never;
        head?: never;
        patch: operations["users_partial_update"];
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get or update the current user's own profile */
        get: operations["users_me_retrieve"];
        /** Get or update the current user's own profile */
        put: operations["users_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Get or update the current user's own profile */
        patch: operations["users_me_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Assignment: {
            readonly id: number;
            readonly class_id: number;
            exercise_id?: number | null;
            readonly assigned_by: number | null;
            /** Format: date-time */
            due_date?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        AssignmentRequest: {
            exercise_id?: number | null;
            /** Format: date-time */
            due_date?: string | null;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        Class: {
            readonly id: number;
            class_name: string;
            teacher_id?: number | null;
            academic_year?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        ClassRequest: {
            class_name: string;
            teacher_id?: number | null;
            academic_year?: string | null;
        };
        ClassStudent: {
            readonly id: number;
            readonly class_id: number;
            readonly student_id: number;
            /** Format: date-time */
            readonly joined_at: string;
        };
        /**
         * @description * `beginner` - Beginner
         *     * `intermediate` - Intermediate
         *     * `advanced` - Advanced
         * @enum {string}
         */
        DifficultyLevelEnum: "beginner" | "intermediate" | "advanced";
        EnrollRequest: {
            student_id: number;
        };
        Exercise: {
            readonly id: number;
            module_id?: number | null;
            title: string;
            exercise_type: components["schemas"]["SkillTypeEnum"];
            prompt_text: string;
            audio_prompt_url?: string | null;
            readonly questions: components["schemas"]["Question"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        ExerciseRequest: {
            module_id?: number | null;
            title: string;
            exercise_type: components["schemas"]["SkillTypeEnum"];
            prompt_text: string;
            audio_prompt_url?: string | null;
        };
        Feedback: {
            readonly id: number;
            submission_id: number;
            readonly reviewer_id: number;
            /** Format: decimal */
            score?: string | null;
            comments?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        FeedbackRequest: {
            submission_id: number;
            /** Format: decimal */
            score?: string | null;
            comments?: string | null;
        };
        LearningModule: {
            readonly id: number;
            title: string;
            description?: string | null;
            difficulty_level?: (components["schemas"]["DifficultyLevelEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly created_by: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        LearningModuleRequest: {
            title: string;
            description?: string | null;
            difficulty_level?: (components["schemas"]["DifficultyLevelEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        LessonPlan: {
            readonly id: number;
            readonly class_id: number;
            title: string;
            objectives?: string | null;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        LessonPlanRequest: {
            title: string;
            objectives?: string | null;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @enum {unknown} */
        NullEnum: null;
        PatchedClassRequest: {
            class_name?: string;
            teacher_id?: number | null;
            academic_year?: string | null;
        };
        PatchedLearningModuleRequest: {
            title?: string;
            description?: string | null;
            difficulty_level?: (components["schemas"]["DifficultyLevelEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        PatchedUserRequest: {
            /** Format: email */
            email?: string;
            full_name?: string;
            avatar_url?: string | null;
            role?: components["schemas"]["RoleEnum"];
        };
        /**
         * @description Self-service / admin update. `status` is only honoured for admins
         *     (enforced in the view).
         */
        PatchedUserUpdateRequest: {
            full_name?: string;
            avatar_url?: string | null;
            status?: components["schemas"]["StatusEnum"];
        };
        Progress: {
            readonly id: number;
            readonly student_id: number;
            readonly module_id: number;
            /** Format: decimal */
            completion_percentage?: string;
            /** Format: date-time */
            last_accessed_at?: string | null;
        };
        ProgressUpsertRequest: {
            module_id: number;
            /** Format: decimal */
            completion_percentage: string;
        };
        Question: {
            readonly id: number;
            exercise_id: number;
            text: string;
            order?: number;
            readonly options: components["schemas"]["QuestionOption"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        QuestionOption: {
            readonly id: number;
            text: string;
            is_correct?: boolean;
            order?: number;
        };
        QuestionOptionRequest: {
            text: string;
            is_correct?: boolean;
            order?: number;
        };
        QuestionRequest: {
            exercise_id: number;
            text: string;
            order?: number;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            full_name: string;
            avatar_url?: string | null;
            role: components["schemas"]["RoleEnum"];
        };
        /**
         * @description * `student` - Student
         *     * `teacher` - Teacher
         *     * `admin` - Admin
         * @enum {string}
         */
        RoleEnum: "student" | "teacher" | "admin";
        /**
         * @description * `writing` - Writing
         *     * `speaking` - Speaking
         *     * `reading` - Reading
         *     * `listening` - Listening
         *     * `quiz` - Quiz
         * @enum {string}
         */
        SkillTypeEnum: "writing" | "speaking" | "reading" | "listening" | "quiz";
        /**
         * @description * `active` - Active
         *     * `suspended` - Suspended
         *     * `inactive` - Inactive
         * @enum {string}
         */
        StatusEnum: "active" | "suspended" | "inactive";
        Submission: {
            readonly id: number;
            exercise_id: number;
            assignment_id?: number | null;
            submission_type: components["schemas"]["SkillTypeEnum"];
            writing_text?: string | null;
            audio_recording_url?: string | null;
            answers?: unknown;
            /** Format: decimal */
            readonly auto_score: string | null;
            readonly student_id: number;
            /** Format: date-time */
            readonly submitted_at: string;
        };
        SubmissionRequest: {
            exercise_id: number;
            assignment_id?: number | null;
            submission_type: components["schemas"]["SkillTypeEnum"];
            writing_text?: string | null;
            audio_recording_url?: string | null;
            answers?: unknown;
        };
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            email: string;
            password: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @default bearer */
            token_type: string;
        };
        TokenRefresh: {
            readonly access: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        User: {
            readonly id: number;
            /** Format: email */
            email: string;
            full_name: string;
            avatar_url?: string | null;
            role: components["schemas"]["RoleEnum"];
            readonly status: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        UserRequest: {
            /** Format: email */
            email: string;
            full_name: string;
            avatar_url?: string | null;
            role: components["schemas"]["RoleEnum"];
        };
        /**
         * @description Self-service / admin update. `status` is only honoured for admins
         *     (enforced in the view).
         */
        UserUpdateRequest: {
            full_name?: string;
            avatar_url?: string | null;
            status?: components["schemas"]["StatusEnum"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Incorrect email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    classes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"][];
                };
            };
        };
    };
    classes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ClassRequest"];
                "multipart/form-data": components["schemas"]["ClassRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    classes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    classes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ClassRequest"];
                "multipart/form-data": components["schemas"]["ClassRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    classes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    classes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedClassRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedClassRequest"];
                "multipart/form-data": components["schemas"]["PatchedClassRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    classes_assignments_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    classes_assignments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AssignmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AssignmentRequest"];
                "multipart/form-data": components["schemas"]["AssignmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    classes_lesson_plans_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlan"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlan"];
                };
            };
        };
    };
    classes_lesson_plans_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonPlanRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonPlanRequest"];
                "multipart/form-data": components["schemas"]["LessonPlanRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlan"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlan"];
                };
            };
        };
    };
    classes_students_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassStudent"];
                };
            };
        };
    };
    classes_students_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EnrollRequest"];
                "multipart/form-data": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassStudent"];
                };
            };
        };
    };
    classes_students_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
                /** @description ID of the student to unenroll */
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrollment removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exercises_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this exercise. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
        };
    };
    exercises_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this exercise. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exercises_submissions_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this exercise. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"][];
                };
            };
        };
    };
    feedback_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["FeedbackRequest"];
                "multipart/form-data": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
        };
    };
    modules_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningModule"][];
                };
            };
        };
    };
    modules_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningModuleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LearningModuleRequest"];
                "multipart/form-data": components["schemas"]["LearningModuleRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningModule"];
                };
            };
        };
    };
    modules_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningModule"];
                };
            };
        };
    };
    modules_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningModuleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LearningModuleRequest"];
                "multipart/form-data": components["schemas"]["LearningModuleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningModule"];
                };
            };
        };
    };
    modules_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    modules_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLearningModuleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLearningModuleRequest"];
                "multipart/form-data": components["schemas"]["PatchedLearningModuleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningModule"];
                };
            };
        };
    };
    modules_exercises_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
        };
    };
    modules_exercises_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ExerciseRequest"];
                "multipart/form-data": components["schemas"]["ExerciseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
        };
    };
    progress_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressUpsertRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProgressUpsertRequest"];
                "multipart/form-data": components["schemas"]["ProgressUpsertRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
        };
    };
    progress_me_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"][];
                };
            };
        };
    };
    submissions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SubmissionRequest"];
                "multipart/form-data": components["schemas"]["SubmissionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
        };
    };
    submissions_feedback_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this submission. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"][];
                };
            };
        };
    };
    submissions_me_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"][];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserUpdateRequest"];
                "multipart/form-data": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
