/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/activity/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent admin activity (audit logs + new users/submissions/feedback)
         * @description Recent admin activity feed (read-only, Admin only).
         */
        get: operations["admin_activity_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System health probe (database check + entity counts)
         * @description System health snapshot (read-only, Admin only).
         */
        get: operations["admin_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai-models/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Admin-managed multimodal-evaluation engine registry (docs.md UC-20/21,
         *     RBAC row 13). Toggling is_active/strictness reconfigures the live AI grader.
         */
        get: operations["ai_models_list"];
        put?: never;
        /**
         * @description Admin-managed multimodal-evaluation engine registry (docs.md UC-20/21,
         *     RBAC row 13). Toggling is_active/strictness reconfigures the live AI grader.
         */
        post: operations["ai_models_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai-models/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Admin-managed multimodal-evaluation engine registry (docs.md UC-20/21,
         *     RBAC row 13). Toggling is_active/strictness reconfigures the live AI grader.
         */
        get: operations["ai_models_retrieve"];
        /**
         * @description Admin-managed multimodal-evaluation engine registry (docs.md UC-20/21,
         *     RBAC row 13). Toggling is_active/strictness reconfigures the live AI grader.
         */
        put: operations["ai_models_update"];
        post?: never;
        /**
         * @description Admin-managed multimodal-evaluation engine registry (docs.md UC-20/21,
         *     RBAC row 13). Toggling is_active/strictness reconfigures the live AI grader.
         */
        delete: operations["ai_models_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Admin-managed multimodal-evaluation engine registry (docs.md UC-20/21,
         *     RBAC row 13). Toggling is_active/strictness reconfigures the live AI grader.
         */
        patch: operations["ai_models_partial_update"];
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email + password
         * @description Email + password -> JWT access/refresh pair.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["classes_list"];
        put?: never;
        post: operations["classes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["classes_retrieve"];
        put: operations["classes_update"];
        post?: never;
        delete: operations["classes_destroy"];
        options?: never;
        head?: never;
        patch: operations["classes_partial_update"];
        trace?: never;
    };
    "/api/classes/{id}/assignments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or create assignments for a class */
        get: operations["classes_assignments_list"];
        put?: never;
        /** List or create assignments for a class */
        post: operations["classes_assignments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{id}/lesson-plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or create lesson plans for a class */
        get: operations["classes_lesson_plans_list"];
        put?: never;
        /** List or create lesson plans for a class */
        post: operations["classes_lesson_plans_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{id}/students/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List students in a class, or enroll one */
        get: operations["classes_students_list"];
        put?: never;
        /** List students in a class, or enroll one */
        post: operations["classes_students_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{id}/students/{student_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a student from a class */
        delete: operations["classes_students_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Role-aware dashboard aggregate (student / teacher / admin)
         * @description Returns a different payload shape per role. Student: due/upcoming assignments, in-progress modules, recent feedback. Teacher: class & student counts, ungraded-submission count, recent activity. Admin: user counts by role and platform totals + recent rows.
         */
        get: operations["dashboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exercises_retrieve"];
        put?: never;
        post?: never;
        delete: operations["exercises_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}/submissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List submissions for an exercise (teacher/admin) */
        get: operations["exercises_submissions_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["feedback_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["modules_list"];
        put?: never;
        post: operations["modules_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["modules_retrieve"];
        put: operations["modules_update"];
        post?: never;
        delete: operations["modules_destroy"];
        options?: never;
        head?: never;
        patch: operations["modules_partial_update"];
        trace?: never;
    };
    "/api/modules/{id}/exercises/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List or create exercises within a module */
        get: operations["modules_exercises_list"];
        put?: never;
        /** List or create exercises within a module */
        post: operations["modules_exercises_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upsert the current student's progress for a module
         * @description Upsert progress for (student, module). POST /api/progress/.
         */
        post: operations["progress_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current student's module progress */
        get: operations["progress_me_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export a class grade report (CSV; PDF deferred) */
        get: operations["reports_grades_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study-materials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Official study-documents library.
         *
         *     Read (list/retrieve) is open to every authenticated, active user (RBAC
         *     row 7 — "Read & Save Study Documents"). Write (create/update/destroy) is
         *     Admin-only (RBAC row 6 — "Manage Official Study Materials Library").
         */
        get: operations["study_materials_list"];
        put?: never;
        /**
         * @description Official study-documents library.
         *
         *     Read (list/retrieve) is open to every authenticated, active user (RBAC
         *     row 7 — "Read & Save Study Documents"). Write (create/update/destroy) is
         *     Admin-only (RBAC row 6 — "Manage Official Study Materials Library").
         */
        post: operations["study_materials_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study-materials/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Official study-documents library.
         *
         *     Read (list/retrieve) is open to every authenticated, active user (RBAC
         *     row 7 — "Read & Save Study Documents"). Write (create/update/destroy) is
         *     Admin-only (RBAC row 6 — "Manage Official Study Materials Library").
         */
        get: operations["study_materials_retrieve"];
        /**
         * @description Official study-documents library.
         *
         *     Read (list/retrieve) is open to every authenticated, active user (RBAC
         *     row 7 — "Read & Save Study Documents"). Write (create/update/destroy) is
         *     Admin-only (RBAC row 6 — "Manage Official Study Materials Library").
         */
        put: operations["study_materials_update"];
        post?: never;
        /**
         * @description Official study-documents library.
         *
         *     Read (list/retrieve) is open to every authenticated, active user (RBAC
         *     row 7 — "Read & Save Study Documents"). Write (create/update/destroy) is
         *     Admin-only (RBAC row 6 — "Manage Official Study Materials Library").
         */
        delete: operations["study_materials_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Official study-documents library.
         *
         *     Read (list/retrieve) is open to every authenticated, active user (RBAC
         *     row 7 — "Read & Save Study Documents"). Write (create/update/destroy) is
         *     Admin-only (RBAC row 6 — "Manage Official Study Materials Library").
         */
        patch: operations["study_materials_partial_update"];
        trace?: never;
    };
    "/api/submissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submissions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}/ai-evaluate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request AI feedback for a submission (UC-17/18)
         * @description Teacher/Admin triggers AI grading on an existing submission. Runs the
         *     active backend SYNCHRONOUSLY (MVP) and writes an is_ai_generated Feedback
         *     row (reviewer=None). Structured to move to an async worker later.
         */
        post: operations["submissions_ai_evaluate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{id}/feedback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List feedback on a submission (owner / reviewer / class teacher / admin) */
        get: operations["submissions_feedback_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/ai-practice/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autonomous AI skill practice (RBAC row 12, UC-09)
         * @description Student practices an exercise off-assignment and gets immediate AI
         *     feedback via the mock backend. Creates a Submission (assignment=None),
         *     derives submission_type from the exercise, then evaluates it.
         */
        post: operations["submissions_ai_practice_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/inbox/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Teacher inbox: submissions across the teacher's own exercises
         * @description Aggregates submissions for every exercise the requesting teacher owns (Exercise.created_by, with module.created_by fallback), including self-practice submissions where assignment is null. Admins see all submissions. Optional filters: status, class_id, exercise_id.
         */
        get: operations["submissions_inbox_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current student's own submissions */
        get: operations["submissions_me_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (admin) — filterable by role/status/search */
        get: operations["users_list"];
        put?: never;
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_retrieve"];
        put: operations["users_update"];
        post?: never;
        delete: operations["users_destroy"];
        options?: never;
        head?: never;
        patch: operations["users_partial_update"];
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get or update the current user's own profile */
        get: operations["users_me_retrieve"];
        /** Get or update the current user's own profile */
        put: operations["users_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Get or update the current user's own profile */
        patch: operations["users_me_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One normalized row in the admin activity feed (read-only). */
        ActivityItem: {
            type: string;
            id: number;
            summary: string;
            /** Format: date-time */
            timestamp: string;
        };
        AiModel: {
            readonly id: number;
            model_name: string;
            endpoint_url: string;
            version_identifier: string;
            is_active?: boolean;
            strictness?: components["schemas"]["StrictnessEnum"];
            readonly updated_by_id: number;
            /** Format: date-time */
            readonly updated_at: string;
        };
        AiModelRequest: {
            model_name: string;
            endpoint_url: string;
            version_identifier: string;
            is_active?: boolean;
            strictness?: components["schemas"]["StrictnessEnum"];
        };
        /**
         * @description Ad-hoc student practice against an exercise — no Assignment required.
         *     Mirrors SubmissionSerializer's writable payload fields.
         */
        AiPracticeRequest: {
            exercise_id: number;
            writing_text?: string | null;
            audio_recording_url?: string | null;
        };
        AiPracticeResult: {
            submission: components["schemas"]["Submission"];
            feedback: components["schemas"]["Feedback"];
        };
        Assignment: {
            readonly id: number;
            readonly class_id: number;
            exercise_id?: number | null;
            readonly assigned_by: number | null;
            /** Format: date-time */
            due_date?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        AssignmentRequest: {
            exercise_id?: number | null;
            /** Format: date-time */
            due_date?: string | null;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        Class: {
            readonly id: number;
            class_name: string;
            teacher_id?: number;
            academic_year?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        ClassRequest: {
            class_name: string;
            teacher_id?: number;
            academic_year?: string | null;
        };
        ClassStudent: {
            readonly id: number;
            readonly class_id: number;
            readonly student_id: number;
            /** Format: date-time */
            readonly joined_at: string;
        };
        Dashboard: {
            role: string;
            /** Format: date-time */
            generated_at: string;
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * @description * `beginner` - Beginner
         *     * `intermediate` - Intermediate
         *     * `advanced` - Advanced
         * @enum {string}
         */
        DifficultyLevelEnum: "beginner" | "intermediate" | "advanced";
        EnrollRequest: {
            student_id: number;
        };
        Exercise: {
            readonly id: number;
            module_id?: number | null;
            title: string;
            exercise_type: components["schemas"]["SkillTypeEnum"];
            prompt_text: string;
            content_text?: string | null;
            audio_prompt_url?: string | null;
            readonly created_by: number;
            readonly questions: components["schemas"]["Question"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        ExerciseRequest: {
            module_id?: number | null;
            title: string;
            exercise_type: components["schemas"]["SkillTypeEnum"];
            prompt_text: string;
            content_text?: string | null;
            audio_prompt_url?: string | null;
        };
        Feedback: {
            readonly id: number;
            submission_id: number;
            readonly reviewer_id: number;
            /** Format: decimal */
            score?: string | null;
            comments?: string | null;
            readonly is_ai_generated: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        FeedbackRequest: {
            submission_id: number;
            /** Format: decimal */
            score?: string | null;
            comments?: string | null;
        };
        /** @description System health snapshot (read-only) — see AdminHealthView. */
        Health: {
            status: string;
            database: string;
            /** Format: double */
            db_latency_ms: number;
            counts: {
                [key: string]: number;
            };
            /** Format: date-time */
            server_time: string;
        };
        LearningModule: {
            readonly id: number;
            title: string;
            description?: string | null;
            difficulty_level?: (components["schemas"]["DifficultyLevelEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly created_by: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        LearningModuleRequest: {
            title: string;
            description?: string | null;
            difficulty_level?: (components["schemas"]["DifficultyLevelEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        LessonPlan: {
            readonly id: number;
            readonly class_id: number;
            title: string;
            objectives?: string | null;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        LessonPlanRequest: {
            title: string;
            objectives?: string | null;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @enum {unknown} */
        NullEnum: null;
        PatchedAiModelRequest: {
            model_name?: string;
            endpoint_url?: string;
            version_identifier?: string;
            is_active?: boolean;
            strictness?: components["schemas"]["StrictnessEnum"];
        };
        PatchedClassRequest: {
            class_name?: string;
            teacher_id?: number;
            academic_year?: string | null;
        };
        PatchedLearningModuleRequest: {
            title?: string;
            description?: string | null;
            difficulty_level?: (components["schemas"]["DifficultyLevelEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
        };
        /**
         * @description Official study document. ``file_url`` is a plain mock string URL — there
         *     is no real upload backend in this MVP, so clients send/receive a URL string
         *     (same convention as ``Exercise.audio_prompt_url``). ``uploaded_by_id`` is
         *     set server-side to the requesting admin and is read-only.
         */
        PatchedStudyMaterialRequest: {
            title?: string;
            file_url?: string;
            description?: string | null;
            class_id?: number | null;
        };
        PatchedUserRequest: {
            /** Format: email */
            email?: string;
            full_name?: string;
            avatar_url?: string | null;
            role?: components["schemas"]["UserRoleEnum"];
        };
        /**
         * @description Self-service / admin update. `status` is only honoured for admins
         *     (enforced in the view).
         */
        PatchedUserUpdateRequest: {
            full_name?: string;
            avatar_url?: string | null;
            status?: components["schemas"]["Status36eEnum"];
        };
        Progress: {
            readonly id: number;
            readonly student_id: number;
            readonly module_id: number;
            /** Format: decimal */
            completion_percentage?: string;
            /** Format: date-time */
            last_accessed_at?: string | null;
        };
        ProgressUpsertRequest: {
            module_id: number;
            /** Format: decimal */
            completion_percentage: string;
        };
        Question: {
            readonly id: number;
            exercise_id: number;
            text: string;
            order?: number;
            readonly options: components["schemas"]["QuestionOption"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        QuestionOption: {
            readonly id: number;
            text: string;
            is_correct?: boolean;
            order?: number;
        };
        QuestionOptionRequest: {
            text: string;
            is_correct?: boolean;
            order?: number;
        };
        QuestionRequest: {
            exercise_id: number;
            text: string;
            order?: number;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            full_name: string;
            avatar_url?: string | null;
            role: components["schemas"]["RegisterRoleEnum"];
        };
        /**
         * @description * `student` - Student
         *     * `teacher` - Teacher
         * @enum {string}
         */
        RegisterRoleEnum: "student" | "teacher";
        /**
         * @description * `writing` - Writing
         *     * `speaking` - Speaking
         *     * `reading` - Reading
         *     * `listening` - Listening
         *     * `quiz` - Quiz
         * @enum {string}
         */
        SkillTypeEnum: "writing" | "speaking" | "reading" | "listening" | "quiz";
        /**
         * @description * `active` - Active
         *     * `suspended` - Suspended
         *     * `inactive` - Inactive
         * @enum {string}
         */
        Status36eEnum: "active" | "suspended" | "inactive";
        /**
         * @description * `pending` - Pending
         *     * `graded` - Graded
         *     * `ai_graded` - AI Graded
         * @enum {string}
         */
        StatusD4fEnum: "pending" | "graded" | "ai_graded";
        /**
         * @description * `lenient` - Lenient
         *     * `standard` - Standard
         *     * `strict` - Strict
         * @enum {string}
         */
        StrictnessEnum: "lenient" | "standard" | "strict";
        /**
         * @description Official study document. ``file_url`` is a plain mock string URL — there
         *     is no real upload backend in this MVP, so clients send/receive a URL string
         *     (same convention as ``Exercise.audio_prompt_url``). ``uploaded_by_id`` is
         *     set server-side to the requesting admin and is read-only.
         */
        StudyMaterial: {
            readonly id: number;
            title: string;
            file_url: string;
            description?: string | null;
            readonly uploaded_by_id: number;
            class_id?: number | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description Official study document. ``file_url`` is a plain mock string URL — there
         *     is no real upload backend in this MVP, so clients send/receive a URL string
         *     (same convention as ``Exercise.audio_prompt_url``). ``uploaded_by_id`` is
         *     set server-side to the requesting admin and is read-only.
         */
        StudyMaterialRequest: {
            title: string;
            file_url: string;
            description?: string | null;
            class_id?: number | null;
        };
        Submission: {
            readonly id: number;
            exercise_id: number;
            assignment_id?: number | null;
            submission_type: components["schemas"]["SkillTypeEnum"];
            writing_text?: string | null;
            audio_recording_url?: string | null;
            answers?: unknown;
            /** Format: decimal */
            readonly auto_score: string | null;
            readonly status: components["schemas"]["StatusD4fEnum"];
            readonly student_id: number;
            /** Format: date-time */
            readonly submitted_at: string;
        };
        /**
         * @description Read-only inbox row: existing submission fields + grading-state
         *     annotations derived from Feedback. Honors docs.md §6 directive #1 —
         *     grading attribution is decided by is_ai_generated, never by assuming a
         *     teacher reviewer exists.
         */
        SubmissionInbox: {
            readonly id: number;
            exercise_id: number;
            assignment_id?: number | null;
            submission_type: components["schemas"]["SkillTypeEnum"];
            writing_text?: string | null;
            audio_recording_url?: string | null;
            answers?: unknown;
            /** Format: decimal */
            readonly auto_score: string | null;
            readonly status: components["schemas"]["StatusD4fEnum"];
            readonly student_id: number;
            /** Format: date-time */
            readonly submitted_at: string;
            readonly is_graded: string;
            readonly grading_source: string;
            readonly latest_score: string;
            readonly student_name: string;
        };
        SubmissionRequest: {
            exercise_id: number;
            assignment_id?: number | null;
            submission_type: components["schemas"]["SkillTypeEnum"];
            writing_text?: string | null;
            audio_recording_url?: string | null;
            answers?: unknown;
        };
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            email: string;
            password: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @default bearer */
            token_type: string;
        };
        TokenRefresh: {
            readonly access: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        User: {
            readonly id: number;
            /** Format: email */
            email: string;
            full_name: string;
            avatar_url?: string | null;
            role: components["schemas"]["UserRoleEnum"];
            readonly status: components["schemas"]["Status36eEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        UserRequest: {
            /** Format: email */
            email: string;
            full_name: string;
            avatar_url?: string | null;
            role: components["schemas"]["UserRoleEnum"];
        };
        /**
         * @description * `student` - Student
         *     * `teacher` - Teacher
         *     * `admin` - Admin
         * @enum {string}
         */
        UserRoleEnum: "student" | "teacher" | "admin";
        /**
         * @description Self-service / admin update. `status` is only honoured for admins
         *     (enforced in the view).
         */
        UserUpdateRequest: {
            full_name?: string;
            avatar_url?: string | null;
            status?: components["schemas"]["Status36eEnum"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    admin_activity_list: {
        parameters: {
            query?: {
                /** @description Max rows to return (default 50, max 200) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityItem"][];
                };
            };
        };
    };
    admin_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ai_models_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiModel"][];
                };
            };
        };
    };
    ai_models_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiModelRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AiModelRequest"];
                "multipart/form-data": components["schemas"]["AiModelRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiModel"];
                };
            };
        };
    };
    ai_models_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ai model. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiModel"];
                };
            };
        };
    };
    ai_models_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ai model. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiModelRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AiModelRequest"];
                "multipart/form-data": components["schemas"]["AiModelRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiModel"];
                };
            };
        };
    };
    ai_models_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ai model. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ai_models_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this ai model. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAiModelRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAiModelRequest"];
                "multipart/form-data": components["schemas"]["PatchedAiModelRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiModel"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Incorrect email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    classes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"][];
                };
            };
        };
    };
    classes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ClassRequest"];
                "multipart/form-data": components["schemas"]["ClassRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    classes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    classes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ClassRequest"];
                "multipart/form-data": components["schemas"]["ClassRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    classes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    classes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedClassRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedClassRequest"];
                "multipart/form-data": components["schemas"]["PatchedClassRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Class"];
                };
            };
        };
    };
    classes_assignments_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    classes_assignments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AssignmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AssignmentRequest"];
                "multipart/form-data": components["schemas"]["AssignmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    classes_lesson_plans_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlan"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlan"];
                };
            };
        };
    };
    classes_lesson_plans_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonPlanRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LessonPlanRequest"];
                "multipart/form-data": components["schemas"]["LessonPlanRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlan"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonPlan"];
                };
            };
        };
    };
    classes_students_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassStudent"];
                };
            };
        };
    };
    classes_students_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EnrollRequest"];
                "multipart/form-data": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassStudent"];
                };
            };
        };
    };
    classes_students_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this class. */
                id: number;
                /** @description ID of the student to unenroll */
                student_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrollment removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dashboard_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    exercises_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this exercise. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
        };
    };
    exercises_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this exercise. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exercises_submissions_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this exercise. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"][];
                };
            };
        };
    };
    feedback_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["FeedbackRequest"];
                "multipart/form-data": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
        };
    };
    modules_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningModule"][];
                };
            };
        };
    };
    modules_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningModuleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LearningModuleRequest"];
                "multipart/form-data": components["schemas"]["LearningModuleRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningModule"];
                };
            };
        };
    };
    modules_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningModule"];
                };
            };
        };
    };
    modules_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningModuleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LearningModuleRequest"];
                "multipart/form-data": components["schemas"]["LearningModuleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningModule"];
                };
            };
        };
    };
    modules_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    modules_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLearningModuleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLearningModuleRequest"];
                "multipart/form-data": components["schemas"]["PatchedLearningModuleRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningModule"];
                };
            };
        };
    };
    modules_exercises_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
        };
    };
    modules_exercises_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this learning module. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ExerciseRequest"];
                "multipart/form-data": components["schemas"]["ExerciseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"][];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
        };
    };
    progress_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressUpsertRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProgressUpsertRequest"];
                "multipart/form-data": components["schemas"]["ProgressUpsertRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
        };
    };
    progress_me_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"][];
                };
            };
        };
    };
    reports_grades_retrieve: {
        parameters: {
            query: {
                /** @description Class to report on. Teachers may only export their own. */
                class_id: number;
                /** @description csv (default, implemented) or pdf (deferred — 501 unless reportlab hook enabled). */
                format?: "csv" | "pdf";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            /** @description Not your class */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Class not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PDF export not enabled */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    study_materials_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyMaterial"][];
                };
            };
        };
    };
    study_materials_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyMaterialRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StudyMaterialRequest"];
                "multipart/form-data": components["schemas"]["StudyMaterialRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyMaterial"];
                };
            };
        };
    };
    study_materials_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyMaterial"];
                };
            };
        };
    };
    study_materials_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyMaterialRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StudyMaterialRequest"];
                "multipart/form-data": components["schemas"]["StudyMaterialRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyMaterial"];
                };
            };
        };
    };
    study_materials_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    study_materials_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this study material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStudyMaterialRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStudyMaterialRequest"];
                "multipart/form-data": components["schemas"]["PatchedStudyMaterialRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyMaterial"];
                };
            };
        };
    };
    submissions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SubmissionRequest"];
                "multipart/form-data": components["schemas"]["SubmissionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
        };
    };
    submissions_ai_evaluate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this submission. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
        };
    };
    submissions_feedback_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this submission. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"][];
                };
            };
            /** @description Not permitted to view this feedback */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submissions_ai_practice_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiPracticeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AiPracticeRequest"];
                "multipart/form-data": components["schemas"]["AiPracticeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiPracticeResult"];
                };
            };
        };
    };
    submissions_inbox_list: {
        parameters: {
            query?: {
                /** @description Filter to submissions whose assignment targets this class */
                class_id?: number;
                /** @description Filter to a single exercise */
                exercise_id?: number;
                /** @description Filter by submission status (stored values): pending | graded | ai_graded */
                status?: "ai_graded" | "graded" | "pending";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionInbox"][];
                };
            };
        };
    };
    submissions_me_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"][];
                };
            };
        };
    };
    users_list: {
        parameters: {
            query?: {
                /** @description Filter by role: admin | teacher | student */
                role?: string;
                /** @description Case-insensitive match on email or full_name */
                search?: string;
                /** @description Filter by status: active | suspended | inactive */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserUpdateRequest"];
                "multipart/form-data": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
}
